---
title: "Indicadores del CBIMA"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
---


```{r setup, include=FALSE}
#-------------------- Paquetes --------------------

library(flexdashboard)
library(dplyr)
library(sf)
library(leaflet)
library(esri2sf)
library(raster)
library(plotly)

```


Row {data-width=400}
-----------------------------------------------------------------------

### Mapa
```{r include=FALSE}

#--------------- URL de geoservicios --------------

url_agfs_limite_cbima <-
  "https://services9.arcgis.com/RrvMEynxDB8hycVO/arcgis/rest/services/gam_limite_cbi_maria_aguilar/FeatureServer/0"

#--------------- Objetos sf y raster --------------

# Límite del CBIMA
sf_limite_cbima <- esri2sf(url_agfs_limite_cbima)
# Capa raster de uso y cobertura de la tierra
raster_infraestructura_verde <- 
  raster("https://raw.githubusercontent.com/atlas-servicios-ecosistemicos-gam/datos/master/infraestructura-verde/cbima/IV_CBI_RIO_MARIA_AGUILAR.TIF") %>%
  aggregate(fact=4, fun=modal) %>%
  projectRaster(crs="+proj=longlat +datum=WGS84") %>%
  crop(sf_limite_cbima) %>%
  mask(sf_limite_cbima)

#---------------- Paletas de colores ---------------

colores_infraestructura_verde <- 
  c(rgb(106,142,88, maxColorValue=255), rgb(64,131,136, maxColorValue=255), 
    rgb(73,230,0,   maxColorValue=255), rgb(105,255,71, maxColorValue=255), 
    rgb(0,83,102,   maxColorValue=255), rgb(255,255,0,  maxColorValue=255), 
    rgb(145,172,128,maxColorValue=255), rgb(217,217,214,maxColorValue=255), 
    rgb(91,63,54,   maxColorValue=255), rgb(109,145,64, maxColorValue=255), 
    rgb(71,106,48,  maxColorValue=255), rgb(255,252,188,maxColorValue=255), 
    rgb(171,205,102,maxColorValue=255), rgb(137,90,68,  maxColorValue=255), 
    rgb(220,212,148,maxColorValue=255)
    )
bins_infraestructura_verde <- c(1, 3, 4, 7, 8, 9, 10, 11, 12, 14, 15, 19, 20, 21, 22)
etiquetas_infraestructura_verde <- 
  c("Bosques y arbolados periurbanos", "Bosques y arbolados en la ribera de los ríos", 
    "Parques y jardines pequeños con árboles", "Campos deportivos y recreativos", 
    "Lagunas estacionales de agua dulce", "Arbolados dispersos", 
    "Terrenos baldíos (matorrales)", "Superficie no pavimentada", 
    "Superficie pavimentada", "Arbolados a lo largo de la vía férrea", 
    "Arbolados a lo largo de autopistas", "Pastos cultivados", 
    "Cultivos perennes", "Cafetales arbolados",
    "Terrenos baldíos (pastos)"
    )
paleta_infraestructura_verde <- 
  colorBin(palette = colores_infraestructura_verde, bins = bins_infraestructura_verde, domain = bins_infraestructura_verde, na.color = "transparent")

```

```{r}
#------------------- Mapa ------------------

leaflet() %>%
  setView((-84.11961 + -83.97383)/2, (9.907672 + 9.94576)/2, 12) %>%
  addProviderTiles(providers$OpenStreetMap.Mapnik, group = "OpenStreetMap") %>%
  addProviderTiles(providers$Stamen.TonerLite, group = "Stamen Toner Lite") %>%
  addProviderTiles(providers$CartoDB.DarkMatter, group = "CartoDB Dark Matter") %>%
  addProviderTiles(providers$Esri.WorldImagery, group = "Imágenes de ESRI") %>%
  addPolygons(
    data = sf_limite_cbima,
    color = "Purple",
    fillColor = "transparent",
    stroke = TRUE,
    weight = 6.0,
    group = "Límite del CBIMA"
  ) %>%
  addRasterImage(
    raster_infraestructura_verde, 
    colors = paleta_infraestructura_verde, 
    group = "Infraestructura verde"
  ) %>%  
  addLayersControl(
    baseGroups = c("OpenStreetMap", "Stamen Toner Lite", "CartoDB Dark Matter", "Imágenes de ESRI"),
    overlayGroups = c("Límite del CBIMA", "Infraestructura verde"),
    options = layersControlOptions(collapsed = TRUE)    
  ) %>%  
  addMiniMap(
    toggleDisplay = TRUE,
    position = "bottomright",
    tiles = providers$OpenStreetMap.Mapnik
  ) %>%
  addScaleBar(
    position = "bottomleft",
    options = scaleBarOptions(imperial = FALSE)
  )

```


### Gráfico
```{r}
library(plotly)

# Vector de tipos de infraestructura
tipos_infraestructura <- c("Infraestructura natural", "Infraestructura gris")

# Vector de superficies de tipo
superficies <- c(56, 44)

superficies_infraestructura <- 
  data.frame(
    tipo = tipos_infraestructura, 
    superficie = superficies
  )

datos <- superficies_infraestructura[,c('tipo', 'superficie')]

fig <- plot_ly(datos, labels = ~tipos_infraestructura, values = ~superficies, type = 'pie')
fig <- fig %>% layout(title = 'Tipo de infraestructura',
                      xaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE),
                      yaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE))

fig

```


Row
-----------------------------------------------------------------------

### % vegetación {.value-box}
```{r}
valueBox(value = "25.7", 
         caption = "% vegetación<br>Moderación extremos clima"
)
```

### % vegetación ribereña {.value-box}
```{r}
valueBox(value = "5.2", 
         caption = "% vegetación ribereña<br>Moderación extremos clima"
)
```

### Superficie verde por habitante (m2/hab) {.value-box}
```{r}
valueBox(value = "54.5", 
         caption = "Superficie verde por habitante<br>Beneficios estéticos"
)
```

### Densidad cobertura árborea (cobertura arbórea/ha) {.value-box}
```{r}
valueBox(value = "0.21", 
         caption = "Densidad cobertura árborea<br>Hábitat para la biodiversidad"
)
```

### % área natural {.value-box}
```{r}
valueBox(value = "21.1", 
         caption = "% área natural<br>Hábitat para la biodiversidad"
)
```

### % área semi-natural {.value-box}
```{r}
valueBox(value = "23.3", 
         caption = "% área semi-natural<br>Hábitat para la biodiversidad"
)
```